title: Vlad's AI Research Blog
description: Exploring AI and cognition through research, implementations, and insights
author: Vladimir Ershov
url: "https://Vladimir-Ershov.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Social links
github_username: Vladimir-Ershov
linkedin_username: vladimir-ershov-33559466

exclude:
  - projects/MLRecap/.pixi/
  - .pixi/
  - projects/MLRecap/

# Show excerpts on homepage
show_excerpts: true

# Additional settings
timezone: Europe/London
permalink: /:categories/:year/:month/:day/:title/

# Navigation (optional - customize as needed)
header_pages:
  - about.md
  - posts.md

# Collections (optional - for better organization)
collections:
  posts:
    output: true
    permalink: /:collection/:name/

# Kramdown settings for better code rendering
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Allow raw HTML and JavaScript in markdown
kramdown:
  parse_block_html: true
  parse_span_html: true