[workspace]
name = "MLRecap"
version = "0.1.0"
authors = ["Vladimir-Ershov <106324080+Vladimir-Ershov@users.noreply.github.com>"]
channels = ["pytorch", "nvidia", "conda-forge"]
platforms = ["linux-64"]
# channel-priority = "disabled"
channel-priority = "strict" 

[dependencies]
ipykernel = ">=6.30.1,<7"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.7.1,<2"
skorch = ">=1.2.0,<2"

[feature.pytorch]
channels = ["pytorch", "nvidia", "conda-forge"]
 #channel-priority = "disabled"
channel-priority = "strict" 

[feature.pytorch.dependencies]
python = "3.9.*"                                # Change to 3.9
pytorch = { version = "2.5.*", channel = "pytorch", build = "*cuda12.4*" }
torchvision = { version = "*", channel = "pytorch", build = "*cu124*" }
torchaudio = { version = "*", channel = "pytorch" }
pytorch-cuda = "12.4.*"                         # CUDA 12.4 for latest PyTorch
ipykernel = "*"
seaborn = "*"
scikit-learn = "*"
# detecto = "*"
pillow = "*"

[environments]
pytorch = { features = ["pytorch"], no-default-feature = true }
